x-shared: &default-env
  env_file:
    - path: infra/conf/.env
      required: true
    - path: infra/conf/.env.local
      required: false

services:
  postgres:
    image: postgres:16-alpine
    container_name: cinecall_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinecall_net
    <<: *default-env

  waha:
    image: devlikeapro/waha:latest
    container_name: cinecall_waha
    restart: always
    ports:
      - "3000:3000"
    networks:
      - cinecall_net
    <<: *default-env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cinecall_backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./init.sql:/app/init.sql:ro
    depends_on:
      - postgres
      - waha
    networks:
      - cinecall_net
    <<: *default-env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: cinecall_frontend
    restart: always
    ports:
      - "8080:3000"
    <<: *default-env

volumes:
  postgres_data:

networks:
  cinecall_net:
    driver: bridge
